### PR TITLE
Bolt 2 clean ups

### PR DESCRIPTION
**Pull request by GwendolenLynch**

### CODE REVIEW

**Comment by bobdenotter** [comment]
Found it! :-)

**Comment by bobdenotter** [comment]
This PR's been open for only 1.5 years now. :-)

**Comment by GwendolenLynch** [comment]
I suppose you want me to rebase a non-existing repo, right? :wink:

**Comment by bobdenotter** [comment]
We'll need to fix this up for V3 anyways. :-)

**Pull request closed without merging**
